apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
  namespace: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
      - name: celery-worker
        image: python:3.11-slim
        command: ["celery"]
        args: ["-A", "glitchtip", "worker", "--loglevel=info"]
        env:
        - name: REDIS_URL
          value: "redis://192.168.178.116:31788"
