apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: plex
spec:
  selector:
    app: sonarr
  ports:
    - name: web
      protocol: TCP
      port: 8989
      targetPort: 8989
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: sonarr-nodeport
  namespace: plex
spec:
  selector:
    app: sonarr
  ports:
    - name: web
      protocol: TCP
      port: 8989
      targetPort: 8989
      nodePort: 32122
  type: NodePort
