apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-run-models
  namespace: financial
spec:
  schedule: "0 11 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: run-models-latest
            image: docker.io/caproni60/financial:run-models-latest
            imagePullPolicy: Always
            envFrom:
              - configMapRef:
                  name: financial-config
          restartPolicy: Never
