apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-content-pvc
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-configuration-pvc
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
