apiVersion: v1
kind: Service
metadata:
  name: plex
  labels:
    app: plex
  namespace: plex
spec:
  type: NodePort
  ports:
  - port: 32400
    targetPort: 32400
    nodePort: 31313
    protocol: TCP
  selector:
    app: plex

---

apiVersion: v1
kind: Service
metadata:
  name: plex-api
  namespace: plex
spec:
  selector:
    app: plex
  ports:
    - name: web
      protocol: TCP
      port: 32400
      targetPort: 32400
  type: ClusterIP
