apiVersion: v1
kind: Service
metadata:
  name: mongodb-internal-service
  labels:
    app: mongodb-internal-service
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: mongodb
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb-service
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    nodePort: 30000
  selector:
    app: mongodb
  type: NodePort

