apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-storageclass
provisioner: kubernetes.io/no-provisioner
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  fsType: ext4
