image:
  repository: ghcr.io/linuxserver/plex
  tag: latest
  pullPolicy: IfNotPresent

persistence:
  config:
    enabled: true
    size: 1Gi
    storageClass: "longhorn"
    accessMode: ReadWriteOnce
  media:
    enabled: true
    size: 100Gi
    storageClass: "longhorn"
    accessMode: ReadWriteOnce

service:
  type: NodePort
  port: 32400
  nodePort: 31313

claimToken: "claim-Z2JUovY_smDcQztV_4s7"

timezone: "Europe/London"
