apiVersion: apps/v1
kind: Deployment
metadata:
  name: glitchtip
  namespace: glitchtip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glitchtip
  template:
    metadata:
      labels:
        app: glitchtip
    spec:
      containers:
        - name: glitchtip
          image: glitchtip/glitchtip:latest
          env:
            - name: REDIS_URL
              value: "redis://192.168.178.116:31788"
            - name: GLITCHTIP_DOMAIN
              value: "http://192.168.178.116:31122"
            - name: ALLOWED_HOSTS
              value: "*"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: glitchtip-database-url
                  key: secret
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: glitchtip-secret-key
                  key: secret
          ports:
            - containerPort: 8080
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - turing2
