apiVersion: v1
kind: Service
metadata:
  name: glitchtip-service
  namespace: glitchtip
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31122
  selector:
    app: glitchtip
