apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: plex
  labels:
    app: lidarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      containers:
        - name: lidarr
          image: lscr.io/linuxserver/lidarr:latest
          ports:
            - containerPort: 8686
              name: web
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /downloads
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - turing4
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: lidarr-configuration-pvc
        - name: media
          persistentVolumeClaim:
            claimName: plex-content-pvc
