apiVersion: v1
kind: Service
metadata:
  name: lidarr
  namespace: plex
spec:
  selector:
    app: lidarr
  ports:
    - name: web
      protocol: TCP
      port: 8686
      targetPort: 8686
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: lidarr-nodeport
  namespace: plex
spec:
  selector:
    app: lidarr
  ports:
    - name: web
      protocol: TCP
      port: 8686
      targetPort: 8686
      nodePort: 32125
  type: NodePort
