apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      nodeSelector:
        pihole: true
      initContainers:
      - name: init-log-dir
        image: busybox
        command: ['sh', '-c', 'mkdir -p /var/log/lighttpd && touch /var/log/lighttpd/access-pihole.log /var/log/lighttpd/error-pihole.log && chown -R www-data:www-data /var/log/lighttpd']
        volumeMounts:
        - name: var-log
          mountPath: /var/log
      containers:
      - name: pihole
        image: pihole/pihole:latest
        ports:
          - containerPort: 80
            hostPort: 80
            protocol: TCP
          - containerPort: 53
            hostPort: 53
            protocol: UDP
          - containerPort: 53
            hostPort: 53
            protocol: TCP
        env:
        - name: TZ
          value: "Europe/London"
        volumeMounts:
        - name: var-log
          mountPath: /var/log
      volumes:
      - name: var-log
        emptyDir: {}
