apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: pihole
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
  selector:
    app: pihole
