apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssd1-pv
spec:
  capacity:
    storage: 1700Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongo-storageclass
  local:
    path: /mnt/ssd
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ubuntu1

