apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: plex
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:latest
          ports:
            - containerPort: 7878
              name: web
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /downloads
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - turing4
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr-configuration-pvc
        - name: media
          persistentVolumeClaim:
            claimName: plex-content-pvc
