apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-configuration-pvc
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrent-downloads-pvc
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
