apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: plex
spec:
  selector:
    app: radarr
  ports:
    - name: web
      protocol: TCP
      port: 7878
      targetPort: 7878
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: radarr-nodeport
  namespace: plex
spec:
  selector:
    app: radarr
  ports:
    - name: web
      protocol: TCP
      port: 7878
      targetPort: 7878
      nodePort: 32123
  type: NodePort
