apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: financial-models-pvc
  namespace: financial
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn
