apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-refresh-materialized-views
  namespace: financial
spec:
  schedule: "0 9 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            cronjob-name: cronjob-refresh-materialized-views
      template:
        spec:
          containers:
          - name: update-stocks-latest
            image: docker.io/caproni60/financial:refresh-materialized-views-latest
            imagePullPolicy: Always
            envFrom:
              - configMapRef:
                  name: financial-config
          restartPolicy: Never
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - turing1
                          - turing2
                          - turing3
                          - turing4
