apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-train-binary-models
  namespace: financial
spec:
  schedule: "0 0 * * 6"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: train-binary-models-latest
            image: docker.io/caproni60/financial:train-binary-models-latest
            imagePullPolicy: Always
            envFrom:
              - configMapRef:
                  name: financial-config
          restartPolicy: Never
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - turing1
                          - turing2
                          - turing3
                          - turing4
