apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-update-stock-database
  namespace: financial
spec:
  schedule: "0 22 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: update-stock-database-latest
            image: docker.io/caproni60/financial:update-stock-database-latest
            imagePullPolicy: Always
            envFrom:
              - configMapRef:
                  name: financial-config
          restartPolicy: Never
