apiVersion: v1
kind: Service
metadata:
  name: openproject-postgres-service
  namespace: openproject
spec:
  selector:
    app: openproject-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 32699
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: openproject-service
  namespace: openproject
spec:
  selector:
    app: openproject
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32700
  type: NodePort

