apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30001  # You can specify a custom NodePort or let Kubernetes assign one
  selector:
    app.kubernetes.io/name: postgres
