apiVersion: v1
kind: Service
metadata:
  name: glitchtip-postgres
  namespace: glitchtip
  labels:
    app: glitchtip-postgres
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30999
    protocol: TCP
  selector:
    app: glitchtip-postgres

