apiVersion: v1
kind: Service
metadata:
  name: jackett-service
  namespace: plex
spec:
  type: NodePort
  ports:
    - port: 9117
      targetPort: 9117
      protocol: TCP
      nodePort: 30117
  selector:
    app: jackett
