apiVersion: v1
kind: Service
metadata:
  name: minecraft-bedrock-server
  namespace: minecraft
spec:
  type: NodePort
  ports:
    - port: 19132
      protocol: UDP
      targetPort: 19132
      nodePort: 31113
  selector:
    app: minecraft-bedrock-server
