apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: plex
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:latest
          ports:
            - containerPort: 8989
              name: web
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: media
              mountPath: /tv
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - turing4
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-configuration-pvc
        - name: downloads
          persistentVolumeClaim:
            claimName: torrent-downloads-pvc
        - name: media
          persistentVolumeClaim:
            claimName: plex-content-pvc
