apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
spec:
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: minio

---

apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
spec:
  type: NodePort
  ports:
    - port: 41139
      targetPort: 41139
      nodePort: 32222
  selector:
    app: minio

