apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: plex
spec:
  selector:
    app: transmission
  ports:
    - name: web
      port: 9091
      targetPort: 9091
    - name: peer
      port: 51413
    - name: peer-udp
      port: 51413
      protocol: UDP
  type: NodePort
