replicaCount: 1

image:
  repository: postgres
  tag: "14"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 100Gi
  storageClass: "longhorn"

resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1"

nodeSelector:
  kubernetes.io/hostname: ubuntu1
  kubernetes.io/hostname: ubuntu2
  kubernetes.io/hostname: ubuntu3

