replicaCount: 1

replication:
  enabled: true
  user: replicator
  password: repl1cator
  primaryHost: my-postgres-primary

image:
  repository: postgres
  tag: "14"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 100Gi
  storageClass: "longhorn"

resources:
  requests:
    memory: "2Gi"
    cpu: "1000m"
  limits:
    memory: "12Gi"
    cpu: "4000m"

nodeSelector:
  kubernetes.io/hostname: turing1
  kubernetes.io/hostname: turing2
  kubernetes.io/hostname: turing3
  kubernetes.io/hostname: turing4

