apiVersion: v1
kind: Service
metadata:
  name: mongodb-clusterip-0
  namespace: mongo
  labels:
    app: mongodb-statefulset-0
spec:
  selector:
    statefulset.kubernetes.io/pod-name: mongodb-statefulset-0-0
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    app: mongodb-statefulset-0

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-clusterip-1
  namespace: mongo
  labels:
    app: mongodb-statefulset-1
spec:
  selector:
    statefulset.kubernetes.io/pod-name: mongodb-statefulset-1-0
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    app: mongodb-statefulset-1

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-clusterip-2
  namespace: mongo
  labels:
    app: mongodb-statefulset-2
spec:
  selector:
    statefulset.kubernetes.io/pod-name: mongodb-statefulset-2-0
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    app: mongodb-statefulset-2

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-nodeport-0
  namespace: mongo
  labels:
    app: mongodb-statefulset-0
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    nodePort: 30001
  selector:
    statefulset.kubernetes.io/pod-name: mongodb-statefulset-0-0
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-nodeport-1
  namespace: mongo
  labels:
    app: mongodb-statefulset-1
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    nodePort: 30002
  selector:
    statefulset.kubernetes.io/pod-name: mongodb-statefulset-1-0
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-nodeport-2
  namespace: mongo
  labels:
    app: mongodb-statefulset-2
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    nodePort: 30003
  selector:
    statefulset.kubernetes.io/pod-name: mongodb-statefulset-2-0
  type: NodePort
