apiVersion: v1
kind: Service
metadata:
  name: headless
  namespace: mongo
  labels:
    app: mongodb-statefulset
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  clusterIP: None
  selector:
    app: mongodb-statefulset

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mongo
  labels:
    app: mongodb-statefulset
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    nodePort: 30000
  selector:
    app: mongodb-statefulset
  type: NodePort
