apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  namespace: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
        - name: transmission
          image: linuxserver/transmission:latest
          ports:
            - containerPort: 9091
              name: web
            - containerPort: 51413
              name: peer
            - containerPort: 51413
              protocol: UDP
              name: peer-udp
          volumeMounts:
            - name: config
              mountPath: /config
            - name: plex-media
              mountPath: /movies
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                 - key: kubernetes.io/hostname
                   operator: In
                   values:
                     - turing4
      volumes:
        - name: config
          emptyDir: {}
        - name: plex-media
          persistentVolumeClaim:
            claimName: plex-content-pvc
